
spring:
  application:
    name: hangman
  jackson:
    default-property-inclusion: NON_ABSENT


com:
  freeman:
    url: freeman-hangman
    database:
      host: localhost
      port: 3306
      database: hangman
      username: root
      password: root
    server:
      url: ${spring.application.name}
      port: 8081

#Logging
logging:
  level:
    root: DEBUG
    reactor:
      netty: DEBUG
